export { default as AutomationCenterPage } from './AutomationCenterPage';
export { DashboardPage } from './DashboardPage';
export { TransactionsPage } from './TransactionsPage';
export { BudgetPage } from './BudgetPage';
export { AnalyticsPage } from './AnalyticsPage';
export { CategoriesPage } from './CategoriesPage';
export { SettingsPage } from './SettingsPage';
export { default as EducationDashboard } from './EducationDashboard';
export { default as EducationContentList } from './EducationContentList';
export { default as EducationContentDetail } from './EducationContentDetail';
export { default as HealthScorePage } from './HealthScorePage';
export { SavingTipsPage } from './SavingTipsPage';
export { default as PersonalizedAdvicePage } from './PersonalizedAdvicePage';