groups:
  - name: finance-tracker-alerts
    rules:
      # 애플리케이션 가용성
      - alert: ApplicationDown
        expr: up{job="finance-tracker-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Finance Tracker Backend is down"
          description: "The Finance Tracker backend has been down for more than 1 minute."

      # 높은 응답 시간
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="finance-tracker-backend"}[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds for more than 2 minutes."

      # 높은 에러율
      - alert: HighErrorRate
        expr: rate(http_requests_total{job="finance-tracker-backend",status_code=~"5.."}[5m]) / rate(http_requests_total{job="finance-tracker-backend"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 2 minutes."

      # 데이터베이스 연결 문제
      - alert: DatabaseConnectionFailure
        expr: rate(database_queries_total{status="error"}[5m]) / rate(database_queries_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High database error rate"
          description: "Database error rate is above 10% for more than 1 minute."

      # 메모리 사용량 경고
      - alert: HighMemoryUsage
        expr: (nodejs_memory_usage_bytes{type="rss"} / 1024 / 1024 / 1024) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Node.js process is using more than 1GB of memory for more than 5 minutes."

      # CPU 사용량 경고
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 5 minutes."

  - name: system-alerts
    rules:
      # 시스템 메모리 부족
      - alert: HighSystemMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High system memory usage"
          description: "System memory usage is above 85% for more than 5 minutes."

      # 디스크 공간 부족
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage"
          description: "Disk usage is above 85% for more than 5 minutes."

  - name: business-alerts
    rules:
      # 비정상적으로 많은 예산 초과
      - alert: UnusualBudgetExceededRate
        expr: rate(budgets_exceeded_total[1h]) > 10
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Unusual number of budget exceeded events"
          description: "More than 10 budget exceeded events per hour for the last 10 minutes."

      # 로그인 실패율 증가
      - alert: HighLoginFailureRate
        expr: rate(user_logins_total{success="false"}[5m]) / rate(user_logins_total[5m]) > 0.3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High login failure rate"
          description: "Login failure rate is above 30% for more than 5 minutes."

      # 사용자 활동 급감
      - alert: LowUserActivity
        expr: active_users_current < 5
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Low user activity"
          description: "Active user count has been below 5 for more than 30 minutes."
